#!/bin/bash

set -e

# Wait for database.
# until pg_isready -h "${POSTGRES_HOST}"
# do
#   echo "Waiting for PostgreSQL ${POSTGRES_HOST}";
#   sleep 1;
# done

export APP_MODULE=${APP_MODULE:-"main:app"}

if [ "$APP_STAGE" == "prod" ]; then
  DEFAULT_GUNICORN_CONF="${APP_DIR}/config/gunicorn_conf.py"
  export GUNICORN_CONF=${GUNICORN_CONF:-$DEFAULT_GUNICORN_CONF}
  exec gunicorn -k uvicorn.workers.UvicornWorker -c "$GUNICORN_CONF" "$APP_MODULE"
else
  HOST=${HOST:-0.0.0.0}
  PORT=${PORT:-80}
  LOG_LEVEL=${LOG_LEVEL:-info}
  exec uvicorn --reload --host $HOST --port $PORT --log-level $LOG_LEVEL "$APP_MODULE"
fi
