"""empty message

Revision ID: 4bba5e2e04c6
Revises: 71ef55ac35bb
Create Date: 2020-01-08 19:21:43.722906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bba5e2e04c6'
down_revision = '71ef55ac35bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galleryimage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('exhibition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exhibition_id'], ['exhibition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_galleryimage_id'), 'galleryimage', ['id'], unique=False)
    op.create_index(op.f('ix_galleryimage_title'), 'galleryimage', ['title'], unique=False)
    op.add_column('gallery', sa.Column('exhibition_id', sa.Integer(), nullable=True))
    op.add_column('gallery', sa.Column('title', sa.String(), nullable=True))
    op.create_index(op.f('ix_gallery_title'), 'gallery', ['title'], unique=False)
    op.create_foreign_key(None, 'gallery', 'exhibition', ['exhibition_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gallery', type_='foreignkey')
    op.drop_index(op.f('ix_gallery_title'), table_name='gallery')
    op.drop_column('gallery', 'title')
    op.drop_column('gallery', 'exhibition_id')
    op.drop_index(op.f('ix_galleryimage_title'), table_name='galleryimage')
    op.drop_index(op.f('ix_galleryimage_id'), table_name='galleryimage')
    op.drop_table('galleryimage')
    # ### end Alembic commands ###
