"""empty message

Revision ID: 71ef55ac35bb
Revises: 
Create Date: 2020-01-08 19:12:45.962308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71ef55ac35bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exhibition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exhibition_id'), 'exhibition', ['id'], unique=False)
    op.create_index(op.f('ix_exhibition_title'), 'exhibition', ['title'], unique=False)
    op.create_table('gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_id'), 'gallery', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gallery_id'), table_name='gallery')
    op.drop_table('gallery')
    op.drop_index(op.f('ix_exhibition_title'), table_name='exhibition')
    op.drop_index(op.f('ix_exhibition_id'), table_name='exhibition')
    op.drop_table('exhibition')
    # ### end Alembic commands ###
